### ISSUE TITLE
I will pay for assistance downloading.

### ISSUE THREAD

**Issue by sekomike910** [rgalloni/Auto-GPT-sandbox-wizard#7]
@rgalloni I have a new laptop coming in a few days and will pay you to walk me through the download process and answer a few questions that I have. My preference would be to have this operate outside of the container as I find those challenging to work through. After trying this version and the Torantulino one, this version far outperforms it for some reason. I just prefer to have it outside the docker and I would like to run three instances running at the same time. 

Would you be open to this?

Thank you!

**Comment by rgalloni** [comment]
@sekomike910 The purpose of this project is not to run AutoGPT outside of a container. Moreover, since the script executed within the container is the latest version of AutoGPT, the improved performance you have experienced is likely due to chance. For specific requests like the one you mentioned, we can communicate through private channels. Please feel free to contact me at [decsmail@gmail.com](mailto:decsmail@gmail.com) for further assistance.
